Develop
MeasureAuthoringTool/cql-antlr-parser pull request #1
Opened 2021-03-25 22:30 UTC by greenemcg

Ready for editor building to go on further.....

2021-03-26 14:20 UTC, AndrewBird81 requested changes

2021-03-26 14:20 UTC, AndrewBird81 commented on .gitignore
> +/tests/*.test.js
Why are we ignoring test.js files?

2021-03-26 14:20 UTC, AndrewBird81 commented on src/antlr/CqlAntlrListener.ts
> +abstract class CreatorBase<T extends CqlText> {
I think we should have one class per file

2021-03-31 18:39 UTC, adongare commented on .github/workflows/npm-publish.yml
> +        uses: actions/setup-node@v2-beta
setup-node@v2 is available now

2021-03-31 18:40 UTC, adongare commented on .github/workflows/unit_test_coverage.yml
> +          coverage-reports: lcov.info
Don't think we need this.

2021-03-31 18:47 UTC, adongare approved these changes

2021-03-31 18:56 UTC, AndrewBird81 approved these changes

2021-03-31 18:56 UTC, merged